apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zuul-operator
  template:
    metadata:
      labels:
        name: zuul-operator
    spec:
      serviceAccountName: zuul-operator
      containers:
        - name: operator
          image: "quay.io/zuul-ci/zuul-operator"
          imagePullPolicy: "IfNotPresent"
